language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

services:
 - xvfb

script: 
  - qmake
  - make --silent
  - ./QTreeWidgetExample1 &
  - sleep 10
  - sudo killall -9 QTreeWidgetExample1
  - ./get_code_cov.sh >/dev/null
  # Codecov
  - codecov >/dev/null
  # OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
